---
- hosts: all
  tasks:
   - name: launching ec2 instance
     ec2:
     key_name: ansible_key
     instance_type: t2.micro
     image: ami-aa5ebdd2
     group: naresh
     vpc_subnet_id: subnet-77a6c52f
     region: us-west-2
